Add reusable CNM library
podaac/cloud-notification-message-schema pull request #24
Opened 2022-03-01 19:47 UTC by jocelynmallon

Add a reusable python library, 'CloudNotificationMessage' for generating valid CNM submission messages.

2022-03-01 21:53 UTC, hkryeung approved these changes

2022-03-03 18:48 UTC, ngachung requested changes
Please include input validation for type, checksumType

2022-03-03 18:48 UTC, ngachung commented on cloudnotificationmessage.py
> +                file['checksumType'] = 'md5'
To allow for all valid checksum types https://github.com/podaac/cloud-notification-message-schema/blob/master/cumulus_sns_schema.json#L30-L40

2022-03-03 20:27 UTC, hkryeung approved these changes

2022-03-04 21:35 UTC, ngachung approved these changes

2022-03-04 21:35 UTC, merged