PODAAC-4307 Added optional dataProcessingType to product.
podaac/cloud-notification-message-schema pull request #28
Opened 2022-03-10 22:15 UTC by ngachung

2022-03-10 22:48 UTC, yenes56 approved these changes

2022-03-10 22:50 UTC, hkryeung approved these changes

2022-03-10 23:41 UTC, mike-gangl requested changes
Can you add this to the README.md file as an optional element?

2022-03-10 23:51 UTC, ngachung commented
README.md has been updated

2022-03-10 23:52 UTC, hkryeung approved these changes

2022-03-11 00:39 UTC, mike-gangl approved these changes

2022-03-11 00:41 UTC, merged